django_projects/mysite/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view()),
    path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

django_projects/mysite/mysite/urls.py
import os

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('', include('ads.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }
         ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings

    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

django_projects/mysite/ads/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models


class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment', related_name='comments_owned')
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       through='Fav', related_name='favorite_ads')

    def __str__(self):
        return self.title


class Fav(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self):
        return '%s likes %s' % (self.user.username, self.ad.title[:10])


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15: return self.text
        return self.text[:11] + ' ...'

django_projects/mysite/ads/forms.py
from ads.humanize import naturalsize
from ads.models import Ad
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Ad
        fields = ['title', 'text', 'price', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance


# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

django_projects/mysite/ads/views.py
from ads.forms import CreateForm, CommentForm
from ads.models import Ad, Comment, Fav
from ads.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View


class AdListView(OwnerListView):
    model = Ad
    template_name = "ads/ad_list.html"

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:
            query = Q(title__contains=strval)
            query.add(Q(text__contains=strval), Q.OR)
            ad_list = Ad.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            ad_list = Ad.objects.all()
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_ads.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [row['id'] for row in rows]
        ctx = {'ad_list': ad_list, 'favorites': favorites, 'search': strval}
        return render(request, self.template_name, ctx)


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = 'ads/ad_detail.html'

    def get(self, request, pk):
        x = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = {'ad': x, 'comments': comments, 'comment_form': comment_form}
        return render(request, self.template_name, context)


class AdDeleteView(OwnerDeleteView):
    model = Ad


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()

        return redirect(self.success_url)


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        f = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response


from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Add PK", pk)
        t = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Delete PK", pk)
        t = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

django_projects/mysite/ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Delete ad</h1>

    <p>Are you sure you want to delete the ad: {{ ad }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

django_projects/mysite/ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
    <style>
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 10;
            display: none;
            background-color: rgba(0, 0, 0, 0.5); /*dim the background*/
        }
    </style>
{% endblock %}
{% block content %}
    {% if ad.content_type %}
        <div id="overlay" class="overlay" style="text-align: center;"
             onclick="document.getElementById('overlay').style.display = 'none';">
            <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
        </div>
    {% endif %}

    <span style="float: right;">
({{ ad.updated_at|naturaltime }})

        {% if ad.owner == user %}
            <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
            <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}

</span>
    <h1>{{ ad.title }}</h1>

    {% if ad.content_type %}
        <img style="float:right; max-width:50%;" src="{% url 'ads:ad_picture' ad.id %}"
             onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}

    <p>
        {{ ad.text }}
    </p>
    <p>
        {{ ad.price }}
    </p>
    <p>
        <a href="{% url 'ads:all' %}">All ads</a>
    </p>
    {% if user.is_authenticated %}
        <br clear="all"/>
        <p>
            {% load crispy_forms_tags %}
        <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="All Forums" onclick="window.location.href='{% url 'ads:all' %}';return false;">
        </form>
        </p>
    {% endif %}
    {% for comment in comments %}
        <p> {{ comment.text }}
            ({{ comment.updated_at|naturaltime }})
            {% if user == comment.owner %}
                <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
            {% endif %}
        </p>
    {% endfor %}
{% endblock %}

django_projects/mysite/ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <p>
    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
    </form>
    </p>
    <script>
        $("#upload_form").submit(function () {
            console.log('Checking file size');
            if (window.File && window.FileReader && window.FileList && window.Blob) {
                var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
                if (file && file.size > {{ form.max_upload_limit }}) {
                    alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
                    return false;
                }
            }
        });
    </script>
{% endblock %}

django_projects/mysite/ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>ads</h1>
    <div style="float:right">
        <form>
            <input type="text" placeholder="Search.." name="search"
                    {% if search %} value="{{ search }}" {% endif %}
            >
            <button type="submit"><i class="fa fa-search"></i></button>
            <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
        </form>
    </div>
    <p>
        {% if ad_list %}
            <ul>
                {% for ad in ad_list %}
                    <li>


                        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
                        {% if ad.owner == user %}
                            (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
                            <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
                        {% endif %}

                        {% if user.is_authenticated %}
                            <a href="#" onclick=
                                    "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
                                    {% if ad.id not in favorites %} style="display: none;" {% endif %}
                               id="favorite_star_{{ ad.id }}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
                            </a>
                            <a href="#" onclick=
                                    "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
                                    {% if ad.id in favorites %} style="display: none;" {% endif %}
                               id="unfavorite_star_{{ ad.id }}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
                            </a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No ads are available.</p>
        {% endif %}
    </p>
    <p>
        <a href="{% url 'ads:ad_create' %}">Add an ad</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
        {% endif %}
    </p>
    <script>
        function favPost(url, thing_id) {
            console.log('Requesting JSON');
            $.post(url, {}, function (rowz) {
                console.log(url, 'finished');
                $("#unfavorite_star_" + thing_id).toggle();
                $("#favorite_star_" + thing_id).toggle();
            }).fail(function (xhr) {
                alert('Url failed with ' + xhr.status + ' ' + url);
            });
        }
    </script>
{% endblock %}

django_projects/mysite/ads/templates/ads/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
    <h1>Delete Comment</h1>

    <p>Are you sure you want to delete</p>
    <p>{{ comment.text }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Yes, delete.">
        <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}