django_projects/mysite/ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view()),
    path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

django_projects/mysite/cats/urls.py
from django.urls import path

from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.CatList.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedList.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),

]

django_projects/mysite/mysite/urls.py
import os

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('', include('ads.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }
         ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings

    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

django_projects/mysite/cats/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class Breed(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

# Create your models here.

django_projects/mysite/cats/forms.py
from cats.models import Breed
from django.forms import ModelForm


# Create the form class.
class BreedForm(ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'

django_projects/mysite/cats/views.py
from cats.forms import BreedForm
from cats.models import Cat, Breed
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.
class CatList(LoginRequiredMixin, View):
    def get(self, request):
        mc = Breed.objects.all().count()
        al = Cat.objects.all()
        ctx = {'breed_count': mc, 'cat_list': al}
        return render(request, 'cats/cat_list.html', ctx)


class BreedList(LoginRequiredMixin, View):
    def get(self, request):
        mc = Breed.objects.all()
        ctx = {'breed_list': mc}
        return render(request, 'cats/breed_list.html', ctx)


# https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#createview
class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'


# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class BreedCreate(LoginRequiredMixin, View):
    template = 'cats/breed_form.html'
    success_url = reverse_lazy('cats:all')

    def get(self, request):
        form = BreedForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = BreedForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)
        breed = form.save()
        return redirect(self.success_url)


# BreedUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class BreedUpdate(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/breed_form.html'

    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=breed)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(request.POST, instance=breed)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)
        form.save()
        return redirect(self.success_url)


class BreedDelete(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/breed_confirm_delete.html'

    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=breed)
        ctx = {'breed': breed}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        breed.delete()
        return redirect(self.success_url)

django_projects/mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

    <h1>Delete breed</h1>

    <p>Are you sure you want to delete the breed: {{ breed }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
    </form>

{% endblock %}

django_projects/mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

django_projects/mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}
{% block content %}
    <h1>breed List</h1>
    {% if breed_list %}
        <ul>
            {% for breed in breed_list %}
                <li>
                    {{ breed.name }}
                    (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
                    <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no breeds in the library.</p>
    {% endif %}
    <p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
    <p>
        <a href="{% url 'cats:all' %}">Back to cats</a>
    </p>
{% endblock %}

django_projects/mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

django_projects/mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
    <h1>cat List</h1>
    {% if cat_list %}
        <ul>
            {% for cat in cat_list %}
                <li>
                    {{ cat.nickname }} ({{ cat.breed }})
                    (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
                    <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
                    {{ cat.comments }} ({{ cat.mileage }} miles)
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no cats in the library.</p>
    {% endif %}
    <p>
        {% if breed_count > 0 %}
            <a href="{% url 'cats:cat_create' %}">Add a cat</a>
        {% else %}
            Please add a breed before you add an cat.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
        <a href="{% url 'cats:breed_create' %}">Add a breed</a>
    </p>
{% endblock %}